### ISSUE TITLE
Rich text READMEs result in messy %descriptions

### ISSUE THREAD

**Issue by mythi** [clearlinux/autospec#145]
Rich text READMEs in github that start with badges links to CI/etc. checks result in ```%description```s that contain URL syntax to those badges.

Seen with, e.g., https://github.com/tpm2-software/tpm2-tss/

**Comment by matthewrsj** [comment]
A solution for badges was explored, but due to the many different formats used we ended up providing a way to override the detected summary via a configuration file. More info can be found in https://github.com/clearlinux/autospec/issues/34 and https://github.com/clearlinux/autospec/pull/81

Also in the README: https://github.com/clearlinux/autospec/blame/master/README.rst#L338

Closing as we have a solution.

**Comment by mythi** [comment]
On Fri, Apr 27, 2018 at 6:51 PM, Matthew Johnson wrote:

> A solution for badges was explored, but due to the many different formats
> used we ended up providing a way to override the detected summary via a
> configuration file. More info can be found in #34
> <https://github.com/clearlinux/autospec/issues/34> and #81
> <https://github.com/clearlinux/autospec/pull/81>
>
>
I'm using ```make autospecnew```. AFAICS the override is not an option with
it.
