### ISSUE TITLE
.so files are distributed in lib subpackage for AVX512 builds

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/autospec#300]
When generating the lib subpackage for a avx512-enabled build, autospec inserts .so files into the lib subpackage instead of in the dev subpackage.

**Comment by gtkramer** [comment]
Added [an issue for diva](https://github.com/clearlinux/diva/issues/110) in response to this.  An example of this can be seen with sundials 3.2.0-7 using latest autospec.

**Comment by phmccarty** [comment]
Phrased a different way, .so files installed under `/usr/lib64/haswell/avx512_1` are added to the `lib` subpackage instead of the proper location, the `dev` subpackage.

This issue does not affect .so files installed to `/usr/lib64` or `/usr/lib64/haswell`, which are properly added to the `dev` subpackage.
